apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapx-config
  namespace: fiapx
data:
  NODE_ENV: production
  API_GATEWAY_PORT: "3001"
  REDIS_HOST: fiapx-redis
  REDIS_PORT: "6379"
  UPLOAD_DIR: /app/uploads
  OUTPUT_DIR: /app/outputs
  TEMP_DIR: /app/temp
  SMTP_HOST: fiapx-mailhog
  SMTP_PORT: "1025"
  SMTP_FROM: noreply@fiapx.local
  DD_TRACE_ENABLED: "true"
  DD_ENV: production
  DD_VERSION: "1.0.0"
  DD_LOGS_INJECTION: "true"
  VIDEO_WORKER_CONCURRENCY: "3"
