apiVersion: v1
kind: Secret
metadata:
  name: fiapx-secrets
  namespace: fiapx
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@fiapx-postgres:5432/fiapx_videos
  JWT_SECRET: your-super-secret-key-change-this-in-production
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
