export const APP_DEFAULTS = {
  apiPort: 3001,
  maxVideoSizeBytes: 50 * 1024 * 1024,
  videoQueueName: 'video-processing',
  videoQueueJobName: 'process-video',
  videoJobAttempts: 3,
  workerConcurrency: 3,
  redisHost: 'localhost',
  redisPort: 6379,
  smtpHost: 'mailhog',
  smtpPort: 1025,
  passwordResetUrl: 'http://localhost:3001/auth/reset-password',
  uploadDir: './uploads',
  outputDir: './outputs',
  tempDir: './temp',
  outboxDispatchIntervalMs: 5000,
  outboxBatchSize: 10,
  outboxClaimTimeoutMs: 60_000,
  appCloudRoleName: 'api-fiapx-hackathon-dev',
  datadogEnv: 'fiapx-hackathon-dev-v1',
  datadogAgentHost: 'localhost',
  datadogTraceAgentPort: '8126',
  datadogService: 'api-fiapx-hackathon-dev',
  logLevel: 'info',
} as const;
